### PR TITLE
Add new cargo bike GraphHopper profile

### LINKED ISSUE #629: Use cargo bike routing profile that is now available in GraphHopper
We are currently reworking the Graphhopper profiles and in the course of this we are going to add a new cargo bike profile. We should use this in the app when the cargo bike profile is selected.

### PR DESCRIPTION
**Pull request by adeveloper-wq**
## If available, link to the ticket

Closes: #629 

❗ Wait with merging until the GraphHopper is properly upgraded. As of now it does not have this profile.

### Author

- [x] Code Review
- [ ] Functionality Tested (iOS and Android + different screens)
- [ ] Light/Dark Mode Tested
- [ ] Performance/Energy Consumption Tested (especially in ride view)

### Reviewer

- [ ] Code Review
- [ ] Functionality Tested (iOS and Android + different screens)
- [ ] Light/Dark Mode Tested
- [ ] Performance/Energy Consumption Tested (especially in ride view)

### CODE REVIEW

**Comment by adeveloper-wq** [comment]
The updated GraphHopper is deployed now. Thus, this can be reviewed now. @PaulPickhardt (OSM and DRN should work).

**Comment by PaulPickhardt** [comment]
@adeveloper-wq tested in production. Only DRN worked. OSM did not have the cargo default profile. Maybe the service is not updated yet in production. I will have a look.

Should it also work in release currently or do we update release later? 
For me, it did not work when testing.

**Comment by adeveloper-wq** [comment]
> Maybe the service is not updated yet in production. I will have a look

Could be.

It should also work in release.

**Comment by PaulPickhardt** [comment]
Release and production OSM is now updated. Works fine!

**Review by PaulPickhardt — APPROVED** [review]

**Pull request merged**
